on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    uses: Dev-kitx/.github/.github/workflows/python-publish-pypi.yml@main
    with:
      package_name: staticnest-cli
      python_version: "3.11"
      test_command: "make setup-env && make run-pytest"
      build_command: "pip install build && pyproject-build"
      